-- MySQL Script generated by MySQL Workbench
-- Thu Sep 22 12:21:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema voto_electronico_int_comercial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema voto_electronico_int_comercial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `voto_electronico_int_comercial` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `voto_electronico_int_comercial` ;

-- -----------------------------------------------------
-- Table `voto_electronico_int_comercial`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico_int_comercial`.`usuario` (
  `idusuario` BIGINT NOT NULL,
  `apellido` VARCHAR(255) NOT NULL,
  `baja_logica` INT NULL DEFAULT NULL,
  `dni` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `UK_ma71x4n4tydibsd9qt0m71le7` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `UK_5171l57faosmj8myawaucatdw` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
